# AI School - Epoch 1 - Checkpoint 2

**Total Points:** 100 points (Main exercises) + 10 bonus points

**Minimum Required:** You need **85/100 points** from the main exercises.

You don't need to complete everything perfectly. The bonus exercises are **optional but recommended** for extra practice with advanced topics.

**Dataset:** `omc_members.csv` : a synthetic (messy) dataset of Open Minds Club member records.

**Submission:** Create a GitHub repo, push your `.ipynb` file and the CSV, submit the repo link in the following form: https://forms.gle/h7Xqa78SHZiPXuM47

*Attempt the bonus if you finish early, and don't stress about perfection - learning is the goal!*

---

## Setup

In [94]:
import pandas as pd
import numpy as np

---

## Part 1: Data Loading & First Inspection

### Exo 1: Load the Data (5 points)

Load `omc_members.csv` into a DataFrame called `df`.

Then display:
- The **shape** of the DataFrame
- The **column names**
- The **data types** of each column

In [95]:

csv_path = "omc_members.csv"
df = pd.read_csv(csv_path)

In [50]:
# Display shape, column names, and dtypes
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data types:\n", df.dtypes)

Shape: (128, 14)
Columns: ['member_id', 'full_name', 'age', 'wilaya', 'university', 'level', 'track', 'role', 'join_date', 'workshops_attended', 'project_score', 'github_profile', 'status', 'email']
Data types:
 member_id                 str
full_name                 str
age                   float64
wilaya                    str
university                str
level                     str
track                     str
role                      str
join_date                 str
workshops_attended      int64
project_score         float64
github_profile            str
status                    str
email                     str
dtype: object

---

### Exo 2: First Look (5 points)

Display:
- The **first 5 rows** of the DataFrame
- A **statistical summary** of the numeric columns
- Use `.info()` to get a concise overview

In [ ]:
# First 5 rows
df.head()

,member_id,full_name,age,wilaya,university,level,track,role,join_date,workshops_attended,project_score,github_profile,status,email
0,OMC-2024-465,Nadine Bensalem,25.0,Sétif,ESI,L1,Web Development,Core Team,2024-04-14,7,NaN,github.com/nadine62,Active,nadine.bensalem@email.com
1,OMC-2024-622,Imane Saidi,26.0,BLIDA,UMBB,M2,AI & Data,Member,2024-07-04,4,16.1,github.com/imane85,Inactive,imane.saidi@email.com
2,OMC-2024-398,Sofiane Ziani,23.0,Béjaïa,Univ. Oran 1,M2,Cybersecurity,Member,2024-02-27,7,15.4,github.com/sofiane45,Active,sofiane.ziani@email.com
3,OMC-2024-766,Wafa Rahmani,23.0,Annaba,ENSIA,M2,Software Engineering,Core Team,2024-09-09,2,11.1,NaN,Active,wafa.rahmani@email.com
4,OMC-2024-345,Nassim Rahmani,25.0,BATNA,ENSIA,M2,Web Development,Member,2024-07-19,0,9.0,github.com/nassim64,Active,nassim.rahmani@email.com

In [ ]:
# Statistical summary
df.describe()

              age  workshops_attended  project_score
count  128.000000          128.000000     116.000000
mean    30.304688            3.500000      13.957759
std     87.099324            2.459114       3.433699
min      0.000000            0.000000       8.000000
25%     20.000000            1.000000      11.300000
50%     21.500000            3.000000      13.350000
75%     25.000000            6.000000      17.200000
max    999.000000            7.000000      20.000000

In [ ]:
# Concise overview
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   member_id           128 non-null    str
 1   full_name           128 non-null    str
 2   age                 128 non-null    float64
 3   wilaya              120 non-null    str
 4   university          122 non-null    str
 5   level               128 non-null    str
 6   track               128 non-null    str
 7   role                128 non-null    str
 8   join_date           128 non-null    str
 9   workshops_attended  128 non-null    int64
 10  project_score       116 non-null    float64
 11  github_profile      113 non-null    str
 12  status              128 non-null    str
 13  email               128 non-null    str
dtypes: float64(2), int64(1), str(11)
memory usage: 14.1 KB

---

### Exo 3: Missing Values Report (10 points)

1. Display the **count** of missing values per column
2. Display the **percentage** of missing values per column (rounded to 2 decimal places)
3. Print the names of columns that have **at least one** missing value

In [ ]:
# Count of missing values per column
missing_counts = df.isna().sum()
missing_counts

member_id              0
full_name              0
age                    0
wilaya                 8
university             6
level                  0
track                  0
role                   0
join_date              0
workshops_attended     0
project_score         12
github_profile        15
status                 0
email                  0
dtype: int64

In [ ]:
# Percentage of missing values per column
missing_percent = (df.isna().mean() * 100).round(2)
missing_percent

member_id              0.00
full_name              0.00
age                    0.00
wilaya                 6.25
university             4.69
level                  0.00
track                  0.00
role                   0.00
join_date              0.00
workshops_attended     0.00
project_score          9.38
github_profile        11.72
status                 0.00
email                  0.00
dtype: float64

In [301]:
# Column names with at least one missing value
cols_with_missing = missing_counts[missing_counts > 0].index.tolist()
cols_with_missing

['wilaya', 'university', 'project_score', 'github_profile']

---

## Part 2: Data Cleaning

### Exo 4: Fix Data Types (15 points)

When you loaded the data, some columns were not stored in the correct type. Fix the following:

- `age` → should be **integer** (it's currently a string like `"22.0"`)
- `workshops_attended` → should be **integer** (it's currently a string)
- `join_date` → should be **datetime**

After converting, print the dtypes to confirm.

**Hint:** Convert `age` to float first, then to int.

In [339]:
# Convert age to integer

df['age'] = df['age'].astype(float).astype('Int64')

In [340]:
# Convert workshops_attended to integer
df['workshops_attended'] = df['workshops_attended'].astype('Int64')

In [341]:
# Convert join_date to datetime
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')

In [342]:
# Confirm dtypes
df.dtypes

member_id                        str
full_name                        str
age                            Int64
wilaya                           str
university                       str
level                            str
track                            str
role                             str
join_date             datetime64[us]
workshops_attended             Int64
project_score                float64
github_profile                   str
status                           str
email                            str
dtype: object

---

### Exo 5: Handle Missing Values (10 points)

Fill missing values as follows:

- `project_score` → fill with the **median** of the column
- `wilaya` → fill with `"Unknown"`
- `university` → fill with `"Unknown"`
- `github_profile` → fill with `"Not Provided"`
- `email` → drop rows where email is missing (we can't contact them!)

After cleaning, confirm there are no more missing values.

In [343]:
# Fill missing project_score with median
median_score = df['project_score'].median()

df['project_score'] = df['project_score'].fillna(median_score)

In [344]:
# Fill missing wilaya and university with 'Unknown'
df['wilaya'] = df['wilaya'].fillna('Unknown')

df['university'] = df['university'].fillna('Unknown')

In [345]:
# Fill missing github_profile with 'Not Provided'
df['github_profile'] = df['github_profile'].fillna('Not Provided')

In [346]:
# Drop rows where email is missing
df = df.dropna(subset=['email'])

In [347]:
# Confirm no more missing values
df.isna().sum()

member_id             0
full_name             0
age                   0
wilaya                0
university            0
level                 0
track                 0
role                  0
join_date             0
workshops_attended    0
project_score         0
github_profile        0
status                0
email                 0
dtype: int64

---

### Exo 6: Remove Duplicates (5 points)

1. Print how many **duplicate rows** exist in the dataset
2. Remove them, keeping the **first** occurrence
3. Print the shape of the DataFrame before and after to confirm

In [348]:
# Count duplicate rows
dupCount = df.duplicated().sum()

dupCount

np.int64(8)

In [ ]:
# Remove duplicates and confirm
before_shape = df.shape

df = df.drop_duplicates(keep='first')

after_shape = df.shape

# show shapes before and after
before_shape, after_shape

AttributeError: 'DataFrame' object has no attribute 'shapebefore_shape'

---

### Exo 7: Standardize Text Columns (10 points)

The `wilaya` and `status` columns have **inconsistent casing** (some values are uppercase, some lowercase, some mixed).

1. Standardize `wilaya` to **title case** (e.g. `"ALGIERS"` → `"Algiers"`)
2. Standardize `status` to **title case** (e.g. `"active"` → `"Active"`)
3. Display the unique values of each column after cleaning to confirm

In [ ]:
# Standardize wilaya to title case
df['wilaya'] = df['wilaya'].str.title()

In [ ]:
# Standardize status to title case
df['status'] = df['status'].str.title()

In [ ]:
# Confirm unique values
{

    'wilaya': df['wilaya'].unique(),

    'status': df['status'].unique()}

{'wilaya': <StringArray>
 [      'Sétif',       'Blida',      'Béjaïa',      'Annaba',       'Batna',
      'Tlemcen',     'Algiers', 'Constantine',  'Tizi Ouzou',        'Oran',
      'Unknown']
 Length: 11, dtype: str,
 'status': <StringArray>
 ['Active', 'Inactive']
 Length: 2, dtype: str}

---

## Part 3: Filtering & Selection

### Exo 8: Boolean Filtering (10 points)

Answer the following questions using boolean indexing:

1. How many members have a `project_score` **greater than 15**?
2. Show all **Core Team** or **Lead** members who are from **Algiers**
3. Show all **Active** members who attended **more than 4 workshops**

In [ ]:
# 1. Members with project_score > 15
count_greater15 = (df['project_score'] > 15).sum()

count_greater15

np.int64(47)

In [ ]:
# 2. Core Team or Lead members from Algiers
core_lead_algiers = df[(df['role'].isin(['Core Team','Lead'])) & (df['wilaya']=='Algiers')]

core_lead_algiers

,member_id,full_name,age,wilaya,university,level,track,role,join_date,workshops_attended,project_score,github_profile,status,email
36,OMC-2024-482,Youcef Mekki,20,Algiers,UDBA,L2,AI & Data,Lead,2024-01-25,0,19.40,github.com/youcef35,Active,youcef.mekki@email.com
77,OMC-2024-084,Oussama Boudiaf,25,Algiers,UDBA,L1,Software Engineering,Lead,2024-03-05,0,11.40,github.com/oussama70,Active,oussama.boudiaf@email.com
98,OMC-2024-784,Mehdi Guerfi,19,Algiers,ENSIA,M1,Web Development,Core Team,2024-08-09,2,13.35,Not Provided,Inactive,mehdi.guerfi@email.com
124,OMC-2024-806,Nadine Mekki,23,Algiers,Univ. Oran 1,M1,AI & Data,Core Team,2024-07-12,4,17.00,github.com/nadine55,Active,nadine.mekki@email.com

In [ ]:
# 3. Active members who attended more than 4 workshops
active_workshops = df[(df['status']=='Active') & (df['workshops_attended'] > 4)]

active_workshops

,member_id,full_name,age,wilaya,university,level,track,role,join_date,workshops_attended,project_score,github_profile,status,email
0,OMC-2024-465,Nadine Bensalem,25,Sétif,ESI,L1,Web Development,Core Team,2024-04-14,7,13.35,github.com/nadine62,Active,nadine.bensalem@email.com
2,OMC-2024-398,Sofiane Ziani,23,Béjaïa,Univ. Oran 1,M2,Cybersecurity,Member,2024-02-27,7,15.40,github.com/sofiane45,Active,sofiane.ziani@email.com
6,OMC-2024-463,Nadine Boudiaf,25,Tlemcen,USTHB,M2,Software Engineering,Member,2024-01-02,7,18.20,github.com/nadine64,Active,nadine.boudiaf@email.com
7,OMC-2024-317,Wafa Ouali,22,Sétif,ENP,M2,Cybersecurity,Member,2024-07-22,6,16.10,github.com/wafa32,Active,wafa.ouali@email.com
9,OMC-2024-017,Ilyes Larbi,19,Algiers,ENSIA,M1,Web Development,Member,2024-02-16,7,17.30,github.com/ilyes75,Active,ilyes.larbi@email.com
13,OMC-2024-624,Meriem Mekki,18,Annaba,ENSIA,M1,Embedded Systems,Member,2024-09-08,5,18.10,github.com/meriem17,Active,meriem.mekki@email.com
16,OMC-2024-992,Cyrine Bensalem,26,Blida,Unknown,L1,Web Development,Core Team,2024-04-05,7,13.35,github.com/cyrine23,Active,cyrine.bensalem@email.com
20,OMC-2024-181,Islem Boukhalfa,26,Algiers,UMBB,L1,Embedded Systems,Member,2024-08-22,5,19.40,github.com/islem66,Active,islem.boukhalfa@email.com
32,OMC-2024-730,Imane Meziane,22,Oran,UDBA,M2,Cybersecurity,Member,2024-03-09,5,12.60,github.com/imane86,Active,imane.meziane@email.com
33,OMC-2024-249,Chaima Saidi,18,Annaba,ESI,L1,Embedded Systems,Member,2024-07-14,7,13.35,github.com/chaima16,Active,chaima.saidi@email.com
35,OMC-2024-440,Amira Bensalem,26,Tizi Ouzou,UMBB,M2,Embedded Systems,Member,2024-02-17,5,8.80,github.com/amira77,Active,amira.bensalem@email.com
39,OMC-2024-459,Youcef Meziane,23,Blida,UMBB,M1,Cybersecurity,Member,2024-06-16,5,13.10,github.com/youcef80,Active,double@@email.com
41,OMC-2024-225,Asma Bensalem,23,Blida,ENSIA,L1,AI & Data,Member,2024-08-02,5,16.80,Not Provided,Active,asma.bensalem@email.com
42,OMC-2024-952,Oussama Mansouri,20,Annaba,USTHB,L2,Web Development,Member,2024-02-24,7,17.80,github.com/oussama78,Active,oussama.mansouri@email.com
43,OMC-2024-091,Houda Larbi,23,Tizi Ouzou,ESI,M1,Web Development,Lead,2024-01-22,7,13.00,github.com/houda34,Active,houda.larbi@email.com
45,OMC-2024-389,Amira Bellal,18,Blida,Univ. Constantine,L3,Embedded Systems,Core Team,2024-09-22,7,9.90,github.com/amira47,Active,amira.bellal@email.com
48,OMC-2024-662,Tarek Benabdallah,19,Tizi Ouzou,USTHB,L3,Software Engineering,Member,2024-04-11,7,10.30,github.com/tarek27,Active,@nodomain.dz
49,OMC-2024-828,Walid Boudaoud,20,Algiers,USTHB,L1,Cybersecurity,Member,2024-07-16,7,13.35,github.com/walid61,Active,missing_domain@
50,OMC-2024-198,Nassim Ouali,20,Blida,ESI,L3,Software Engineering,Core Team,2024-09-13,5,19.30,github.com/nassim24,Active,nassim.ouali@email.com
53,OMC-2024-595,Rima Khelif,18,Oran,Univ. Oran 1,L3,Software Engineering,Member,2024-09-04,6,18.80,github.com/rima34,Active,rima.khelif@email.com
62,OMC-2024-827,Fatima Boukhalfa,21,Béjaïa,ESI,M1,AI & Data,Core Team,2024-05-27,5,14.90,github.com/fatima18,Active,fatima.boukhalfa@email.com
63,OMC-2024-416,Walid Benali,25,Blida,ENP,L2,Embedded Systems,Lead,2024-06-15,7,13.30,github.com/walid37,Active,walid.benali@email.com
65,OMC-2024-324,Rima Cherif,25,Tizi Ouzou,UMBB,L3,Embedded Systems,Member,2024-05-15,5,19.10,github.com/rima19,Active,rima.cherif@email.com
66,OMC-2024-664,Nour Boukhalfa,20,Blida,Univ. Oran 1,L1,Cybersecurity,Member,2024-01-10,7,13.35,github.com/nour40,Active,nour.boukhalfa@email.com
68,OMC-2024-926,Asma Ziani,20,Tlemcen,Univ. Constantine,M1,Software Engineering,Lead,2024-07-17,6,19.60,github.com/asma35,Active,asma.ziani@email.com
75,OMC-2024-726,Tarek Benali,26,Béjaïa,UMBB,L3,Embedded Systems,Member,2024-06-20,5,16.00,github.com/tarek25,Active,tarek.benali@email.com
80,OMC-2024-460,Malek Benali,22,Oran,USTHB,L3,Cybersecurity,Lead,2024-03-18,6,13.35,github.com/malek46,Active,malek.benali@email.com
83,OMC-2024-792,Cyrine Meziane,19,Unknown,ESI,M1,Software Engineering,Member,2024-06-06,5,12.30,github.com/cyrine95,Active,cyrine.meziane@email.com
90,OMC-2024-357,Wafa Ouali,25,Tizi Ouzou,ESI,L2,Software Engineering,Member,2024-08-10,6,17.80,Not Provided,Active,wafa.ouali@email.com
92,OMC-2024-178,Feriel Hadjadj,20,Oran,Unknown,M1,Embedded Systems,Lead,2024-08-22,5,18.40,github.com/feriel90,Active,feriel.hadjadj@email.com
95,OMC-2024-896,Imane Boudaoud,24,Béjaïa,Univ. Constantine,L1,Cybersecurity,Member,2024-03-03,7,17.40,github.com/imane43,Active,imane.boudaoud@email.com
96,OMC-2024-638,Lotfi Boukhalfa,21,Algiers,UMBB,L3,Web Development,Member,2024-05-15,7,9.50,Not Provided,Active,invalid@email.org
101,OMC-2024-255,Karim Mekki,19,Unknown,UMBB,M2,Embedded Systems,Member,2024-08-10,6,11.70,github.com/karim89,Active,karim.mekki@email.com
102,OMC-2024-717,Cyrine Benali,23,Sétif,ENP,L1,Web Development,Lead,2024-01-20,7,18.00,github.com/cyrine46,Active,cyrine.benali@email.com
106,OMC-2024-250,Sofiane Guerfi,22,Tlemcen,Univ. Oran 1,L3,AI & Data,Member,2024-06-06,7,13.35,github.com/sofiane43,Active,sofiane.guerfi@email.com
110,OMC-2024-094,Rayan Boudaoud,19,Constantine,ENSIA,M1,Web Development,Member,2024-07-13,7,14.30,github.com/rayan80,Active,rayan.boudaoud@email.com
112,OMC-2024-187,Rayan Larbi,19,Sétif,UDBA,L2,Embedded Systems,Member,2024-06-25,6,11.30,Not Provided,Active,rayan.larbi@email.com
113,OMC-2024-739,Imane Khelif,25,Sétif,UDBA,L2,Embedded Systems,Core Team,2024-05-25,7,10.80,github.com/imane40,Active,user@@email.dz
114,OMC-2024-409,Wafa Boudaoud,24,Tizi Ouzou,Univ. Oran 1,L3,Software Engineering,Member,2024-03-22,7,8.80,github.com/wafa20,Active,wafa.boudaoud@email.com

---

### Exo 9: Selection with `.isin()` and `.loc[]` (10 points)

1. Use `.isin()` to filter members whose `track` is either `"AI & Data"` or `"Cybersecurity"`. How many are there?
2. Use `.loc[]` to display only the `full_name`, `track`, and `project_score` columns for **M1 and M2** level members.

In [ ]:
# 1. Filter by track using .isin()
tracks_mask = df['track'].isin(['AI & Data','Cybersecurity'])

filtered_tracks = df[tracks_mask]
filtered_tracks.shape[0]

40

In [ ]:
# 2. M1 and M2 members — selected columns using .loc[]
m12 = df.loc[df['level'].isin(['M1','M2']), ['full_name','track','project_score']]

m12

               full_name                 track  project_score
1            Imane Saidi             AI & Data          16.10
2          Sofiane Ziani         Cybersecurity          15.40
3           Wafa Rahmani  Software Engineering          11.10
4         Nassim Rahmani       Web Development           9.00
6         Nadine Boudiaf  Software Engineering          18.20
7             Wafa Ouali         Cybersecurity          16.10
8        Meriem Boudaoud         Cybersecurity          17.80
9            Ilyes Larbi       Web Development          17.30
13          Meriem Mekki      Embedded Systems          18.10
14          Feriel Larbi         Cybersecurity          13.35
15        Meriem Meziane       Web Development          10.80
17           Amina Saidi  Software Engineering           9.30
22       Youcef Mansouri         Cybersecurity          18.20
24            Nour Larbi  Software Engineering          18.00
27        Besma Boudaoud  Software Engineering          12.40
29        Oussama Guerfi         Cybersecurity          18.80
31           Rima Khelif             AI & Data          11.40
32         Imane Meziane         Cybersecurity          12.60
35        Amira Bensalem      Embedded Systems           8.80
37      Djamila Mansouri       Web Development          11.30
39        Youcef Meziane         Cybersecurity          13.10
40          Chaima Mekki       Web Development          16.60
43           Houda Larbi       Web Development          13.00
44    Cyrine Benabdallah      Embedded Systems          12.60
52       Walid Boukhalfa  Software Engineering          17.20
56            Amina Hadj             AI & Data           8.30
57            Nour Ouali      Embedded Systems          12.90
59           Adem Khelif             AI & Data          17.20
62      Fatima Boukhalfa             AI & Data          14.90
67          Meriem Ziani      Embedded Systems          17.50
68            Asma Ziani  Software Engineering          19.60
70        Nour Boukhalfa      Embedded Systems          18.70
73           Amine Saidi         Cybersecurity          11.90
78   Yasmine Benabdallah         Cybersecurity          13.40
83        Cyrine Meziane  Software Engineering          12.30
89       Meriem Mansouri      Embedded Systems          13.50
91           Rayan Mekki             AI & Data          13.60
92        Feriel Hadjadj      Embedded Systems          18.40
98          Mehdi Guerfi       Web Development          13.35
101          Karim Mekki      Embedded Systems          11.70
104            Sara Hadj  Software Engineering          17.30
105         Sara Boudiaf      Embedded Systems          20.00
109           Wafa Saidi             AI & Data          18.30
110       Rayan Boudaoud       Web Development          14.30
111      Oussama Hadjadj       Web Development          12.90
115        Tarek Hadjadj         Cybersecurity          15.40
117          Nour Khelif         Cybersecurity          16.70
118       Fatima Boudiaf             AI & Data          13.10
119          Karim Larbi       Web Development           8.30
120       Cyrine Meziane       Web Development          11.90
121        Adem Bensalem  Software Engineering           9.40
123           Amina Hadj       Web Development          19.80
124         Nadine Mekki             AI & Data          17.00
125        Ayoub Hadjadj       Web Development          13.35
126          Wafa Khelif      Embedded Systems          13.35
127    Ilyes Benabdallah      Embedded Systems          18.00

---

### Exo 10: String Filtering (10 points)

Use `.str` methods to answer:

1. Find all members whose `full_name` **starts with the letter 'A'**
2. Find all members whose `email` **contains `benali`** (case-insensitive)
3. How many members have a `github_profile` that is **not** `"Not Provided"`?

**Hint:** For question 3, you can combine `.str` filtering or just use a comparison.

In [ ]:
# 1. Names starting with 'A'
names_A = df[df['full_name'].str.startswith('A', na=False)]

names_A

,member_id,full_name,age,wilaya,university,level,track,role,join_date,workshops_attended,project_score,github_profile,status,email
11,OMC-2024-360,Amira Rahmani,20,Constantine,Univ. Oran 1,L1,Cybersecurity,Core Team,2024-01-03,3,12.50,Not Provided,Active,amira.rahmani@email.com
17,OMC-2024-356,Amina Saidi,20,Tizi Ouzou,ESI,M2,Software Engineering,Member,2024-07-27,7,9.30,github.com/amina56,Inactive,amina.saidi@email.com
35,OMC-2024-440,Amira Bensalem,26,Tizi Ouzou,UMBB,M2,Embedded Systems,Member,2024-02-17,5,8.80,github.com/amira77,Active,amira.bensalem@email.com
41,OMC-2024-225,Asma Bensalem,23,Blida,ENSIA,L1,AI & Data,Member,2024-08-02,5,16.80,Not Provided,Active,asma.bensalem@email.com
45,OMC-2024-389,Amira Bellal,18,Blida,Univ. Constantine,L3,Embedded Systems,Core Team,2024-09-22,7,9.90,github.com/amira47,Active,amira.bellal@email.com
56,OMC-2024-513,Amina Hadj,18,Batna,ESI,M2,AI & Data,Member,2024-06-20,4,8.30,github.com/amina39,Active,amina.hadj@email.com
59,OMC-2024-684,Adem Khelif,23,Annaba,Univ. Oran 1,M2,AI & Data,Member,2024-04-10,3,17.20,github.com/adem42,Active,adem.khelif@email.com
64,OMC-2024-666,Amine Ouali,21,Béjaïa,Univ. Oran 1,L3,Embedded Systems,Lead,2024-09-02,1,10.80,github.com/amine97,Active,amine.ouali@email.com
68,OMC-2024-926,Asma Ziani,20,Tlemcen,Univ. Constantine,M1,Software Engineering,Lead,2024-07-17,6,19.60,github.com/asma35,Active,asma.ziani@email.com
71,OMC-2024-892,Adem Benabdallah,19,Unknown,Unknown,L2,Software Engineering,Lead,2024-03-18,0,15.20,github.com/adem72,Active,invalid@email.net
73,OMC-2024-765,Amine Saidi,23,Oran,Unknown,M1,Cybersecurity,Core Team,2024-05-01,0,11.90,github.com/amine17,Active,amine.saidi@email.com
74,OMC-2024-123,Amira Hadj,18,Sétif,ENSIA,L2,Embedded Systems,Core Team,2024-04-17,5,13.35,github.com/amira15,Inactive,amira.hadj@email.com
76,OMC-2024-413,Ayoub Boudaoud,25,Annaba,UMBB,L2,Web Development,Member,2024-03-14,2,11.30,github.com/ayoub41,Active,ayoub.boudaoud@email.com
82,OMC-2024-699,Amina Larbi,19,Tizi Ouzou,ESI,L3,Embedded Systems,Member,2024-08-01,4,19.70,Not Provided,Active,amina.larbi@email.com
87,OMC-2024-379,Adem Ouali,25,Tlemcen,ESI,L1,Cybersecurity,Member,2024-01-22,1,11.30,github.com/adem94,Inactive,adem.ouali@email.com
99,OMC-2024-594,Amina Khelif,20,Tizi Ouzou,USTHB,L1,Web Development,Member,2024-09-28,2,8.70,github.com/amina75,Active,amina.khelif@email.com
121,OMC-2024-721,Adem Bensalem,20,Béjaïa,USTHB,M2,Software Engineering,Core Team,2024-02-05,4,9.40,github.com/adem23,Active,@nodomain.dz
123,OMC-2024-458,Amina Hadj,24,Tizi Ouzou,UDBA,M2,Web Development,Member,2024-08-11,3,19.80,Not Provided,Active,amina.hadj@email.com
125,OMC-2024-004,Ayoub Hadjadj,26,Blida,ENSIA,M1,Web Development,Core Team,2024-07-18,0,13.35,Not Provided,Active,ayoub.hadjadj@email.com

In [ ]:
# 2. Emails containing 'benali'
emails_benali = df[df['email'].str.contains('benali', case=False, na=False)]

emails_benali

,member_id,full_name,age,wilaya,university,level,track,role,join_date,workshops_attended,project_score,github_profile,status,email
5,OMC-2024-808,Feriel Benali,23,Blida,ENSIA,L2,Web Development,Member,2024-03-04,0,9.60,github.com/feriel55,Active,feriel.benali@email.com
63,OMC-2024-416,Walid Benali,25,Blida,ENP,L2,Embedded Systems,Lead,2024-06-15,7,13.30,github.com/walid37,Active,walid.benali@email.com
75,OMC-2024-726,Tarek Benali,26,Béjaïa,UMBB,L3,Embedded Systems,Member,2024-06-20,5,16.00,github.com/tarek25,Active,tarek.benali@email.com
80,OMC-2024-460,Malek Benali,22,Oran,USTHB,L3,Cybersecurity,Lead,2024-03-18,6,13.35,github.com/malek46,Active,malek.benali@email.com
102,OMC-2024-717,Cyrine Benali,23,Sétif,ENP,L1,Web Development,Lead,2024-01-20,7,18.00,github.com/cyrine46,Active,cyrine.benali@email.com
103,OMC-2024-655,Karim Benali,19,Blida,UMBB,L2,Cybersecurity,Core Team,2024-02-22,1,15.10,github.com/karim14,Active,karim.benali@email.com

In [ ]:
# 3. Members with a real GitHub profile
github_real = df[df['github_profile'] != 'Not Provided']

github_real.shape[0]

106

---

## Part 4: Exploratory Analysis

### Exo 11: Value Counts & Distributions (10 points)

1. Which **3 wilayas** have the most members? Display the count for each.
2. What is the distribution of members across **tracks**? Show as percentages (normalized).
3. How many members are **Active** vs **Inactive**?

In [ ]:
# 1. Top 3 wilayas by member count
top3_wilayas = df['wilaya'].value_counts().nlargest(3)

top3_wilayas

wilaya
Blida         21
Tizi Ouzou    15
Sétif         14
Name: count, dtype: int64

In [ ]:
# 2. Track distribution as percentages
track_distribution = df['track'].value_counts(normalize=True) * 100

track_distribution

track
Embedded Systems        24.166667
Web Development         23.333333
Cybersecurity           20.000000
Software Engineering    19.166667
AI & Data               13.333333
Name: proportion, dtype: float64

In [ ]:
# 3. Active vs Inactive count
status_counts = df['status'].value_counts()

status_counts

status
Active      102
Inactive     18
Name: count, dtype: int64

---

### Exo 12: Group-Level Statistics (10 points)

Use `.groupby()` to answer the following:

1. What is the **average `project_score`** per `track`? Sort from highest to lowest.
2. What is the **average number of workshops attended** per `level` (L1, L2, L3, M1, M2)?
3. Which `role` has the **highest median `project_score`**?

In [ ]:
# 1. Average project_score per track
avg_score_by_track = df.groupby('track')['project_score'].mean().sort_values(ascending=False)

avg_score_by_track

track
AI & Data               15.153125
Embedded Systems        14.456897
Software Engineering    13.934783
Cybersecurity           13.904167
Web Development         13.164286
Name: project_score, dtype: float64

In [ ]:
# 2. Average workshops attended per level
avg_workshops_by_level = df.groupby('level')['workshops_attended'].mean()

avg_workshops_by_level

level
L1    3.772727
L2    2.652174
L3    4.105263
M1    3.214286
M2    3.642857
Name: workshops_attended, dtype: Float64

In [ ]:
# 3. Role with highest median project_score
median_score_by_role = df.groupby('role')['project_score'].median()

top_role = median_score_by_role.idxmax()
{ 'top_role': top_role, 'median_score': median_score_by_role[top_role] }

{'top_role': 'Lead', 'median_score': np.float64(15.2)}

---

## Part 5: Bonus — Optional

### Bonus 1: Email Validator (3 points)

Remember the email validator you wrote in **Checkpoint 1.1**? Time to bring it back — but this time inside a Pandas DataFrame.

The `email` column contains some invalid entries that slipped through. Use the **same regex rules** from Checkpoint 1.1:

- Contains exactly one `@`
- Has characters before and after `@`
- Only contains letters, numbers, dots, and underscores before `@`
- Ends with `.com`, `.dz`, or `.edu`

Your tasks:
1. Write the function `is_valid_email(email)` using `re`
2. Apply it to the `email` column to create a new boolean column called `email_valid`
3. Print how many emails are **valid** and how many are **invalid**
4. Display the rows where the email is **invalid** — show only `full_name` and `email`

**Hint:** Use `.apply()` to apply your function across the column.

In [ ]:
import re

def is_valid_email(email):
    # regex: start with allowed chars, one @, allowed domain and ending
    pattern = r"^[A-Za-z0-9._]+@[A-Za-z0-9._]+\.(com|dz|edu)$"
    return bool(re.match(pattern, email))

In [ ]:
# Apply the function to create the email_valid column
df['email_valid'] = df['email'].apply(is_valid_email)

df[['email','email_valid']].head()

                       email  email_valid
0  nadine.bensalem@email.com         True
1      imane.saidi@email.com         True
2    sofiane.ziani@email.com         True
3     wafa.rahmani@email.com         True
4   nassim.rahmani@email.com         True

In [ ]:
# Count valid vs invalid
df['email_valid'].value_counts()

email_valid
True     105
False     15
Name: count, dtype: int64

In [ ]:
# Display invalid rows (full_name and email only)
invalid_emails = df[~df['email_valid']]

invalid_emails[['full_name','email']]

             full_name                   email
8      Meriem Boudaoud       double@@email.com
14        Feriel Larbi          no_at_sign.com
26       Sofiane Ziani     spaces in@email.com
39      Youcef Meziane       double@@email.com
48   Tarek Benabdallah            @nodomain.dz
49      Walid Boudaoud         missing_domain@
57          Nour Ouali  special!char@email.com
71    Adem Benabdallah       invalid@email.net
96     Lotfi Boukhalfa       invalid@email.org
97     Rayan Boukhalfa     spaces in@email.com
109         Wafa Saidi         missing_domain@
113       Imane Khelif          user@@email.dz
115      Tarek Hadjadj            no_tld@email
121      Adem Bensalem            @nodomain.dz
122     Bilal Bensalem          no_at_sign.com

---

### Bonus 2: Detect & Handle Outliers (4 points)

The `age` column has some clearly invalid values (e.g. someone is 150 years old).

1. Display the rows where `age` is **outside the range [17, 30]**
2. Replace those invalid ages with `NaN` using `.loc[]`
3. Fill the NaN ages with the **median** age
4. Confirm the min and max age are now within valid range

In [ ]:
# 1. Display outlier rows
outliers = df[(df['age'] < 17) | (df['age'] > 30)]

outliers

Empty DataFrame
Columns: [member_id, full_name, age, wilaya, university, level, track, role, join_date, workshops_attended, project_score, github_profile, status, email, email_valid]
Index: []

In [ ]:
# 2. Replace invalid ages with NaN
df.loc[(df['age'] < 17) | (df['age'] > 30), 'age'] = pd.NA

In [ ]:
# 3. Fill NaN ages with median
median_age = df['age'].median()

df['age'] = df['age'].fillna(median_age)

In [ ]:
# 4. Confirm valid range
(df['age'].min(), df['age'].max())

(np.int64(18), np.int64(26))

---

### Bonus 3: Top Performers (3 points)

Create a new DataFrame called `top_performers` that contains only members who satisfy **all** of the following:

- `status` is `"Active"`
- `project_score` is in the **top 10%** of all scores
- `workshops_attended` is **greater than or equal to 5**

Display their `full_name`, `track`, `project_score`, and `workshops_attended`, sorted by `project_score` descending.

**Hint:** Use `df['project_score'].quantile(0.9)` to get the 90th percentile.

In [ ]:
# Build top_performers DataFrame
threshold = df['project_score'].quantile(0.9)

top_performers = df[(df['status'] == 'Active') &
                    (df['project_score'] >= threshold) &
                    (df['workshops_attended'] >= 5)][
                        ['full_name', 'track', 'project_score', 'workshops_attended']
                    ]

top_performers = top_performers.sort_values('project_score', ascending=False)

---

## Acknowledgments

- Notebook authored by: Open Minds Club - AI Leadership
- Dataset: Synthetic OMC member data generated by Claude for educational purposes
- Workshop content inspired by Pandas official documentation: https://pandas.pydata.org/docs/